name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout the current branch"
        uses: actions/checkout@v4
      - name: "set up golang"
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: "Build the binary"
        run: make build
      - name: "Run unit tests"
        run: make test
      - name: "Run integration tests"
        run: make test-integration
