name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the binary
      run: make build

    - name: Run unit tests
      run: make test

    - name: Run integration tests
      run: make test-integration
